## Exercícios

Link para Dataset: https://www.kaggle.com/datasets/matheusfreitag/gas-prices-in-brazil

In [1]:
from pathlib import Path

import pandas as pd

## Neste projeto, trabalharemos com dois arquivos csvs separados, contendo informações sobre o preço da gasolina no Brasil. 

### 1. Carregue os conjuntos de dados "gasolina_2000+.csv" e "gasolina_2010+.csv" em dois DataFrames diferentes e combine-os em um único DataFrame.

In [2]:
dir = Path.cwd().parents[2].joinpath('data_files', 'csv')

if not dir.exists():
    dir = (
        Path.cwd()
        / r'Analisando Dados com Pandas & SQL'
        / 'projetos'
        / 'analise-precos-gasolina'
    )

display(dir.exists())
dir

True

PosixPath('/home/brito/projetos/treinamentos/academia-jedi/data_files/csv')

In [3]:
df1 = pd.read_csv(dir / 'gasolina_2000+.csv', index_col=0)
df1

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52802,2010-12-26,2011-01-01,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,574,R$/l,1.983,0.086,1.779,2.280,0.255,0.043,1.728,0.04,1.609,1.8536,0.023
52803,2010-12-26,2011-01-01,SUDESTE,SAO PAULO,ÓLEO DIESEL,1871,R$/l,1.966,0.070,1.699,2.399,0.261,0.036,1.705,0.045,1.5764,1.969,0.026
52804,2010-12-26,2011-01-01,SUL,PARANA,ÓLEO DIESEL,469,R$/l,1.946,0.058,1.799,2.109,0.19,0.030,1.756,0.038,1.659,1.9268,0.022
52805,2010-12-26,2011-01-01,SUL,RIO GRANDE DO SUL,ÓLEO DIESEL,419,R$/l,2.052,0.059,1.890,2.310,0.267,0.029,1.785,0.039,1.677,1.9172,0.022
52806,2010-12-26,2011-01-01,SUL,SANTA CATARINA,ÓLEO DIESEL,328,R$/l,2.018,0.066,1.849,2.210,0.225,0.033,1.793,0.042,1.7,1.8854,0.023

In [4]:
df2 = pd.read_csv(dir / 'gasolina_2010+.csv', index_col=0)
df2

/tmp/ipykernel_149437/3565186876.py:1: DtypeWarning: Columns (12,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df2=pd.read_csv(dir/'gasolina_2010+.csv', index_col=0)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
9256,2011-01-02,2011-01-08,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,2.030,0.003,2.020,2.050,0.411,0.001,1.619,0.013,1.6111,1.6411,0.008
9257,2011-01-02,2011-01-08,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.717,0.102,1.490,1.990,0.225,0.059,1.492,0.069,1.3221,1.6201,0.046
9258,2011-01-02,2011-01-08,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,141,R$/l,1.848,0.148,1.590,2.490,0.326,0.080,1.522,0.105,1.2833,1.7486,0.069
9259,2011-01-02,2011-01-08,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,132,R$/l,1.893,0.108,1.699,2.199,0.191,0.057,1.702,0.04,1.5915,1.79,0.024
9260,2011-01-02,2011-01-08,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,2.026,0.084,1.749,2.100,0.268,0.041,1.758,0.042,1.63,1.848,0.024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [5]:
df = pd.concat([df1, df2])
df

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

### 2.Investigue as colunas e entenda o conjunto de dados usando o head() e info()

In [6]:
df.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  object
 1   DATA FINAL                     120823 non-null  object
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           120823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: float64(5), int64(1), object(12)
memory usage: 17.5+ MB

### 3. Selecione a terceira entrada da coluna DATA INICIAL e verifique seu tipo.

In [8]:
df['DATA INICIAL']

0         2004-05-09
1         2004-05-09
2         2004-05-09
3         2004-05-09
4         2004-05-09
             ...
120818    2021-04-25
120819    2021-04-25
120820    2021-04-25
120821    2021-04-25
120822    2021-04-25
Name: DATA INICIAL, Length: 120823, dtype: object

### 4. Você deve ter percebido que as colunas DATA INICIAL e DATA FINAL estão formatadas como string. Utilizando o método pd.to_datetime(), converta ambas colunas para Timestamp / Datetime.

In [9]:
pd.to_datetime(df['DATA INICIAL'])

0        2004-05-09
1        2004-05-09
2        2004-05-09
3        2004-05-09
4        2004-05-09
            ...
120818   2021-04-25
120819   2021-04-25
120820   2021-04-25
120821   2021-04-25
120822   2021-04-25
Name: DATA INICIAL, Length: 120823, dtype: datetime64[ns]

In [10]:
df['DATA INICIAL'] = pd.to_datetime(df['DATA INICIAL'])
df['DATA FINAL'] = pd.to_datetime(df['DATA FINAL'])

### 5. Crie uma nova coluna para representar o ano e o mês(aaaa-mm), utilizando a coluna DATA FINAL como referência.

In [11]:
df['DATA FINAL'].dt.year
df['DATA FINAL'].apply(lambda x: f'{x:%Y-%m}')
df['AAAA-MM'] = df['DATA FINAL'].apply(lambda x: f'{x:%Y-%m}')

### 6. Utilizando o value_counts(), liste todos os tipos de produtos contidos na base de dados.

In [12]:
df.columns

Index(['DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO', 'PRODUTO',
       'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO',
       'AAAA-MM'],
      dtype='object')

In [13]:
df.PRODUTO.unique()

array(['ETANOL HIDRATADO', 'GASOLINA COMUM', 'GLP', 'GNV', 'ÓLEO DIESEL',
       'ÓLEO DIESEL S10', 'OLEO DIESEL', 'OLEO DIESEL S10',
       'GASOLINA ADITIVADA'], dtype=object)

### 7. Filtre o DataFrame para obter apenas dados da 'GASOLINA COMUM'. Grave em uma nova variável.

In [14]:
df[df.PRODUTO == 'GASOLINA COMUM']

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,AAAA-MM
12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,1.990,2.070,0.318,0.003,1.711,0.02,1.651,1.7427,0.012,2004-05
12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,1.850,2.220,0.296,0.031,1.729,0.036,1.6643,1.915,0.021,2004-05
12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,2.000,2.540,0.472,0.028,1.886,0.068,1.75,2.0713,0.036,2004-05
12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,1.970,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018,2004-05
12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,2.000,2.159,0.35,0.016,1.74,0.042,1.6789,1.918,0.024,2004-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120721,2021-04-25,2021-05-01,NORTE,RORAIMA,GASOLINA COMUM,12,R$/l,5.364,0.065,5.310,5.530,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120722,2021-04-25,2021-05-01,SUL,SANTA CATARINA,GASOLINA COMUM,119,R$/l,5.051,0.251,4.640,5.599,-99999.0,0.050,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120724,2021-04-25,2021-05-01,NORDESTE,SERGIPE,GASOLINA COMUM,34,R$/l,5.586,0.088,5.410,5.699,-99999.0,0.016,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120725,2021-04-25,2021-05-01,NORTE,TOCANTINS,GASOLINA COMUM,20,R$/l,5.751,0.160,5.578,6.119,-99999.0,0.028,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05

### 8. Qual o preço médio de revenda da gasolina em agosto de 2008?

In [17]:
a2008 = df['DATA FINAL'].dt.year == 2008
df[a2008]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,AAAA-MM
5071,2007-12-30,2008-01-05,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,1.907,0.046,1.779,1.959,0.422,0.024,1.485,0.073,1.329,1.5772,0.049,2008-01
5072,2007-12-30,2008-01-05,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.621,0.111,1.459,1.950,0.299,0.068,1.322,0.058,1.1374,1.5422,0.044,2008-01
5073,2007-12-30,2008-01-05,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,140,R$/l,1.520,0.144,1.310,1.850,0.226,0.095,1.294,0.076,1.15,1.4504,0.059,2008-01
5074,2007-12-30,2008-01-05,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,133,R$/l,1.825,0.053,1.630,1.959,0.374,0.029,1.451,0.055,1.2989,1.652,0.038,2008-01
5075,2007-12-30,2008-01-05,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,1.697,0.097,1.520,1.999,0.183,0.057,1.514,0.065,1.3699,1.7689,0.043,2008-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50021,2008-12-21,2008-12-27,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,595,R$/l,2.081,0.075,1.920,2.679,0.19,0.036,1.891,0.027,1.821,1.982,0.014,2008-12
50022,2008-12-21,2008-12-27,SUDESTE,SAO PAULO,ÓLEO DIESEL,1805,R$/l,2.103,0.052,1.920,2.390,0.206,0.025,1.897,0.031,1.8,2.0154,0.016,2008-12
50023,2008-12-21,2008-12-27,SUL,PARANA,ÓLEO DIESEL,485,R$/l,2.073,0.058,1.940,2.270,0.17,0.028,1.903,0.031,1.7982,1.9751,0.016,2008-12
50024,2008-12-21,2008-12-27,SUL,RIO GRANDE DO SUL,ÓLEO DIESEL,478,R$/l,2.195,0.058,2.049,2.398,0.229,0.026,1.966,0.037,1.8535,2.0858,0.019,2008-12
50025,2008-12-21,2008-12-27,SUL,SANTA CATARINA,ÓLEO DIESEL,339,R$/l,2.144,0.049,2.038,2.290,0.218,0.023,1.926,0.03,1.8638,2.0181,0.016,2008-12

In [23]:
gas = df['PRODUTO'].str.contains('GASOLINA')

df[a2008 & gas]['PREÇO MÉDIO REVENDA'].mean()

np.float64(2.6046061253561255)

### 9. Qual o preço médio de revenda da gasolina em maio de 2014 em São Paulo?

In [35]:
a2014 = df['AAAA-MM'].str.contains('2014-05')
df['ESTADO']
sp = df['ESTADO'] == 'SAO PAULO'
df[a2014 & gas & sp]
df[a2014 & gas & sp]['PREÇO MÉDIO REVENDA'].mean()

np.float64(2.8822)

### 10. Você conseguiria descobrir em qual(quais) estado(s) a gasolina ultrapassou a barreira dos R$ 5,00? E quando isso ocorreu?

In [46]:
brl5 = df['PREÇO MÉDIO REVENDA'] > 5

df[brl5 & gas].sort_values(by=['AAAA-MM', 'ESTADO'])

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,AAAA-MM
98201,2018-05-20,2018-05-26,NORTE,ACRE,GASOLINA COMUM,39,R$/l,5.053,0.184,4.930,5.459,0.797,0.036,4.256,0.132,4.07,4.4685,0.031,2018-05
98347,2018-05-27,2018-06-02,NORTE,ACRE,GASOLINA COMUM,11,R$/l,5.035,0.133,4.890,5.400,0.799,0.026,4.236,0.152,4.07,4.4542,0.036,2018-06
98493,2018-06-03,2018-06-09,NORTE,ACRE,GASOLINA COMUM,39,R$/l,5.038,0.197,4.840,5.459,0.664,0.039,4.374,0.084,4.2316,4.576,0.019,2018-06
98646,2018-06-10,2018-06-16,NORTE,ACRE,GASOLINA COMUM,38,R$/l,5.031,0.206,4.840,5.459,0.686,0.041,4.345,0.081,4.2149,4.518,0.019,2018-06
98797,2018-06-17,2018-06-23,NORTE,ACRE,GASOLINA COMUM,39,R$/l,5.036,0.202,4.890,5.470,0.718,0.040,4.318,0.093,4.1833,4.518,0.022,2018-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120697,2021-04-25,2021-05-01,NORDESTE,SERGIPE,GASOLINA ADITIVADA,29,R$/l,5.713,0.128,5.410,5.899,-99999.0,0.022,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120724,2021-04-25,2021-05-01,NORDESTE,SERGIPE,GASOLINA COMUM,34,R$/l,5.586,0.088,5.410,5.699,-99999.0,0.016,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120698,2021-04-25,2021-05-01,NORTE,TOCANTINS,GASOLINA ADITIVADA,11,R$/l,5.886,0.124,5.759,6.099,-99999.0,0.021,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120725,2021-04-25,2021-05-01,NORTE,TOCANTINS,GASOLINA COMUM,20,R$/l,5.751,0.160,5.578,6.119,-99999.0,0.028,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05

### 11. Qual a média de preço dos estados da região sul em 2012?

In [57]:
gc = df['PRODUTO'] == 'GASOLINA COMUM'
sul = df['REGIÃO'] == 'SUL'
a2012 = df['DATA FINAL'].dt.year == 2012
df[sul & gas]['PREÇO MÉDIO REVENDA'].mean()
# df[sul & gc]['PREÇO MÉDIO REVENDA'].mean()

np.float64(3.168968923418424)

### 12. Você conseguiria obter uma tabela contendo a variação percentual ano a ano para o estado do Rio de Janeiro?

In [ ]:
rj = df['ESTADO'] == 'RIO DE JANEIRO'
media_anual_rj = (
    df[rj & gc]
    .groupby(by=[df['DATA FINAL'].dt.year])['PREÇO MÉDIO REVENDA']
    .mean()
)
media_anual_rj

DATA FINAL
2004    2.171939
2005    2.338588
2006    2.561365
2007    2.532077
2008    2.546731
2009    2.564980
2010    2.647788
2011    2.832698
2012    2.852827
2013    2.995442
2014    3.132115
2015    3.537471
2016    3.917736
2017    4.102308
2018    4.855077
2019    4.855096
2020    4.761295
2021    5.588778
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [79]:
"""Ultimo preço do ano."""
rj_ano_gc = (
    df[rj & gc]
    .groupby(by=[df['DATA FINAL'].dt.year])['PREÇO MÉDIO REVENDA']
    .last()
)
rj_ano_gc

DATA FINAL
2004    2.296
2005    2.508
2006    2.531
2007    2.540
2008    2.565
2009    2.607
2010    2.660
2011    2.849
2012    2.877
2013    3.072
2014    3.206
2015    3.862
2016    4.002
2017    4.548
2018    4.812
2019    4.995
2020    4.929
2021    6.099
Name: PREÇO MÉDIO REVENDA, dtype: float64

### Deslocamento de valores

In [81]:
rj_ano_gc.shift(1)

DATA FINAL
2004      NaN
2005    2.296
2006    2.508
2007    2.531
2008    2.540
2009    2.565
2010    2.607
2011    2.660
2012    2.849
2013    2.877
2014    3.072
2015    3.206
2016    3.862
2017    4.002
2018    4.548
2019    4.812
2020    4.995
2021    4.929
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [105]:
rj_indice_aumento_anual = rj_ano_gc / rj_ano_gc.shift(1) - 1
rj_indice_aumento_anual = rj_indice_aumento_anual.fillna(0).apply(
    lambda x: f'{x:.2%}',
)
rj_indice_aumento_anual

DATA FINAL
2004     0.00%
2005     9.23%
2006     0.92%
2007     0.36%
2008     0.98%
2009     1.64%
2010     2.03%
2011     7.11%
2012     0.98%
2013     6.78%
2014     4.36%
2015    20.46%
2016     3.63%
2017    13.64%
2018     5.80%
2019     3.80%
2020    -1.32%
2021    23.74%
Name: PREÇO MÉDIO REVENDA, dtype: object

### DESAFIO: Crie uma tabela contendo uma serie temporal com a diferença absoluta e percentual entre os valores mais baratos e caros. Apresente também ao lado os estados na qual os maiores e menores preços foram registrados.

In [134]:
df[gas].groupby(by='AAAA-MM').max()['PREÇO MÉDIO REVENDA']
df[gas].groupby(by='AAAA-MM').min()['PREÇO MÉDIO REVENDA']
desafio = pd.DataFrame(
    data={
        'MAX': df[gas].groupby(by='AAAA-MM').max()['PREÇO MÉDIO REVENDA'],
        'MIN': df[gas].groupby(by='AAAA-MM').min()['PREÇO MÉDIO REVENDA'],
    },
)
desafio['PREÇO_MÉDIO'] = desafio.MAX / desafio.MIN
desafio['ABS_DIFF'] = desafio.MAX - desafio.MIN
desafio['PERCENT_DIFF'] = desafio.ABS_DIFF / desafio.MIN
idx_max = df.groupby('AAAA-MM')['PREÇO MÉDIO REVENDA'].idxmax()
idx_min = df.groupby('AAAA-MM')['PREÇO MÉDIO REVENDA'].idxmin()
display(df.loc[idx_max, 'ESTADO'])
desafio['MIN_VALUE_UF'] = df.loc[idx_min, 'ESTADO'].values
desafio['MAX_VALUE_UF'] = df.loc[idx_max, 'ESTADO'].values
desafio

24145            ACRE
24226            ACRE
24442            ACRE
24523            ACRE
24631            ACRE
             ...
118421    MATO GROSSO
118943          AMAPA
119656           ACRE
120200    MATO GROSSO
120736    MATO GROSSO
Name: ESTADO, Length: 204, dtype: object

,MAX,MIN,PREÇO_MÉDIO,ABS_DIFF,PERCENT_DIFF,MIN_VALUE_UF,MAX_VALUE_UF
AAAA-MM,,,,,,,
2004-05,2.438,1.888,1.291314,0.550,0.291314,SAO PAULO,ACRE
2004-06,2.496,1.912,1.305439,0.584,0.305439,SAO PAULO,ACRE
2004-07,2.545,1.936,1.314566,0.609,0.314566,SAO PAULO,ACRE
2004-08,2.560,2.030,1.261084,0.530,0.261084,PERNAMBUCO,ACRE
2004-09,2.570,2.031,1.265387,0.539,0.265387,PERNAMBUCO,ACRE
...,...,...,...,...,...,...,...
2021-01,5.247,3.830,1.369974,1.417,0.369974,MATO GROSSO,MATO GROSSO
2021-02,5.855,4.121,1.420772,1.734,0.420772,MATO GROSSO,AMAPA
2021-03,6.688,4.579,1.460581,2.109,0.460581,MATO GROSSO,ACRE
2021-04,6.251,4.777,1.308562,1.474,0.308562,MATO GROSSO,MATO GROSSO
2021-05,6.258,4.867,1.285802,1.391,0.285802,MATO GROSSO,MATO GROSSO

### Quais estado possuem maiores preços?

In [ ]:
desafio.MAX_VALUE_UF.value_counts()

MAX_VALUE_UF
MATO GROSSO    192
ACRE            11
AMAPA            1
Name: count, dtype: int64

### Quais estados com menores preços

In [ ]:
desafio.MIN_VALUE_UF.value_counts()

MIN_VALUE_UF
SAO PAULO              100
RIO DE JANEIRO          30
MATO GROSSO             26
SANTA CATARINA          17
PERNAMBUCO              10
PARANA                   8
RIO GRANDE DO NORTE      5
ESPIRITO SANTO           5
MINAS GERAIS             1
GOIAS                    1
BAHIA                    1
Name: count, dtype: int64