# Projeto final

Bem vindo ao projeto final do curso/módulo de Pandas.
Neste projeto, você deve responder a um conjunto de perguntas feitas a dois conjuntos de dados:

1. [Obesity among adults by country, 1975-2016](https://www.kaggle.com/amanarora/obesity-among-adults-by-country-19752016/)
2. [GDP Per Person (1901-2011)](https://www.kaggle.com/divyansh22/gdp-per-person-19012011?select=GDP.csv)

Tais conjuntos de dados são públicos foram publicados no Kaggle. Mais instruções sobre cada um deles podem ser encontrados nos links acima. Você também os encontrará na pasta `Datasets`, dentro de nossas apostilas.

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

## Perguntas - Obesity among adults by country, 1975-2016

In [2]:
path = Path.cwd().parents[2]/'data_files'/'csv'
path

PosixPath('/home/brito/projetos/treinamentos/academia-jedi/data_files/csv')

In [3]:
df_obesity = pd.read_csv(path/"obesity_cleaned.csv", index_col=0)

- Limpe os dados do DataFrame, criando uma coluna de nome 'Obesity' que conterá os valores de obesidade. Transforme em float as colunas que porventura foram importadas como string.

In [4]:
df_obesity.head()

       Country  Year    Obesity (%)         Sex
0  Afghanistan  1975  0.5 [0.2-1.1]  Both sexes
1  Afghanistan  1975  0.2 [0.0-0.6]        Male
2  Afghanistan  1975  0.8 [0.2-2.0]      Female
3  Afghanistan  1976  0.5 [0.2-1.1]  Both sexes
4  Afghanistan  1976  0.2 [0.0-0.7]        Male

In [5]:
df_obesity.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24570 entries, 0 to 24569
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Country      24570 non-null  object
 1   Year         24570 non-null  int64
 2   Obesity (%)  24570 non-null  object
 3   Sex          24570 non-null  object
dtypes: int64(1), object(3)
memory usage: 959.8+ KB

In [6]:
df_obesity.columns = df_obesity.columns.str.upper().str.replace(' ', '')

In [8]:
df_obesity['OBESITY(%)'].replace('[\[\]-]', ' ', regex=True).str.split()
df_obesity['OBESITY(%)'].replace('[\[\]-]', ' ', regex=True).str.split(expand=True)
df_obesity['OBESITY(%)'].replace('[\[\]-]', ' ', regex=True).str.split(expand=True)[[0,1,2]]
df_obesity[['percent', 'minor', 'major']] = df_obesity['OBESITY(%)'].replace('No data', '0 0 0').replace('[\[\]-]', ' ', regex=True).str.split(expand=True)[[0,1,2]].apply(pd.to_numeric)
# df_obesity=df_obesity.astype({'percent': 'Float64', 'minor': 'Float64', 'major': 'Float64'})
df_obesity.columns = df_obesity.columns.str.upper().str.replace(' ', '')
df_obesity.dtypes
df_obesity.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24570 entries, 0 to 24569
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   COUNTRY     24570 non-null  object
 1   YEAR        24570 non-null  int64
 2   OBESITY(%)  24570 non-null  object
 3   SEX         24570 non-null  object
 4   PERCENT     24570 non-null  float64
 5   MINOR       24570 non-null  float64
 6   MAJOR       24570 non-null  float64
dtypes: float64(3), int64(1), object(3)
memory usage: 1.5+ MB

- Qual o percentual médio de obesidade por sexo no mundo no ano de 2015?

In [11]:
a2015 = df_obesity.YEAR == 2015
male = df_obesity.SEX == 'Male'
feme = df_obesity.SEX == 'Female'
df_obesity[a2015].groupby('SEX')['PERCENT'].mean()

SEX
Both sexes    19.108205
Female        22.429744
Male          15.652821
Name: PERCENT, dtype: float64

- Quais são os 5 países com a maior e a menor taxa de aumento nos índices de obesidade no período observado?

In [25]:
display(df_obesity)
display('Maior taxa')
display(df_obesity.sort_values(by='PERCENT', ascending=False).COUNTRY.unique()[:5])
display('Menor taxa')
df_obesity.sort_values(by='PERCENT', ascending=True).COUNTRY.unique()[:5]

           COUNTRY  YEAR        OBESITY(%)         SEX  PERCENT  MINOR  MAJOR
0      Afghanistan  1975     0.5 [0.2-1.1]  Both sexes      0.5    0.2    1.1
1      Afghanistan  1975     0.2 [0.0-0.6]        Male      0.2    0.0    0.6
2      Afghanistan  1975     0.8 [0.2-2.0]      Female      0.8    0.2    2.0
3      Afghanistan  1976     0.5 [0.2-1.1]  Both sexes      0.5    0.2    1.1
4      Afghanistan  1976     0.2 [0.0-0.7]        Male      0.2    0.0    0.7
...            ...   ...               ...         ...      ...    ...    ...
24565     Zimbabwe  2015     4.5 [2.4-7.6]        Male      4.5    2.4    7.6
24566     Zimbabwe  2015  24.8 [18.9-31.3]      Female     24.8   18.9   31.3
24567     Zimbabwe  2016  15.5 [12.0-19.2]  Both sexes     15.5   12.0   19.2
24568     Zimbabwe  2016     4.7 [2.5-8.0]        Male      4.7    2.5    8.0
24569     Zimbabwe  2016  25.3 [19.1-32.0]      Female     25.3   19.1   32.0

[24570 rows x 7 columns]

'Maior taxa'

array(['Nauru', 'Cook Islands', 'Palau', 'Marshall Islands', 'Tuvalu'],
      dtype=object)

'Menor taxa'

array(['Monaco', 'South Sudan', 'San Marino', 'Sudan', 'Viet Nam'],
      dtype=object)

- Quais os países com maiores e menores níveis percetuais de obesidade em 2015?

In [34]:
df_obesity[a2015]['PERCENT'].max()
df_obesity[a2015 & (df_obesity[a2015]['PERCENT']==df_obesity[a2015]['PERCENT'].max())]

      COUNTRY  YEAR        OBESITY(%)     SEX  PERCENT  MINOR  MAJOR
15116   Nauru  2015  63.1 [55.5-70.3]  Female     63.1   55.5   70.3

- Qual a diferença média percentual de obesidade entre sexos ao longo dos anos para o Brasil?

In [49]:
brasil_obesity = df_obesity[df_obesity.COUNTRY == 'Brazil']
display(brasil_obesity)

female=brasil_obesity.SEX == 'Female'
male=brasil_obesity.SEX == 'Male'
brasil_obesity.loc[female, 'PERCENT'] - brasil_obesity.loc[male, 'PERCENT']

     COUNTRY  YEAR        OBESITY(%)         SEX  PERCENT  MINOR  MAJOR
2898  Brazil  1975     5.2 [3.3-7.9]  Both sexes      5.2    3.3    7.9
2899  Brazil  1975     3.0 [1.4-5.7]        Male      3.0    1.4    5.7
2900  Brazil  1975    7.3 [4.0-12.0]      Female      7.3    4.0   12.0
2901  Brazil  1976     5.5 [3.5-8.1]  Both sexes      5.5    3.5    8.1
2902  Brazil  1976     3.2 [1.5-5.8]        Male      3.2    1.5    5.8
...      ...   ...               ...         ...      ...    ...    ...
3019  Brazil  2015  18.0 [13.9-22.6]        Male     18.0   13.9   22.6
3020  Brazil  2015  24.9 [20.3-29.8]      Female     24.9   20.3   29.8
3021  Brazil  2016  22.1 [18.7-25.7]  Both sexes     22.1   18.7   25.7
3022  Brazil  2016  18.5 [14.1-23.5]        Male     18.5   14.1   23.5
3023  Brazil  2016  25.4 [20.4-30.7]      Female     25.4   20.4   30.7

[126 rows x 7 columns]

2899   NaN
2900   NaN
2902   NaN
2903   NaN
2905   NaN
        ..
3017   NaN
3019   NaN
3020   NaN
3022   NaN
3023   NaN
Name: PERCENT, Length: 84, dtype: float64

- Você conseguiria plotar um gráfico mostrando a evolução da obesidade para ambos sexos no mundo?

In [ ]:
df_both.plot()

## Perguntas - GDP Per Person (1901-2011)

In [ ]:
df_gdp = pd.read_csv("Datasets/GDP.csv", decimal=".")

- Limpe o conjunto de dados, convertendo strings em datas ou float, quando necessário.

- Você conseguiria informar o primeiro valor registrado de cada país?

- Informe as regiões com maiores crescimentos de PIB per capita no século passado.

- Preecha os anos ausentes em cada país com uma estimativa, baseada na diferença entre o próximo registro e o anterior.

### DESAFIOS
- Você conseguiria criar um mapa do gdp ou da obesidade no mundo ao longo dos anos?

- Há uma relação entre níveis de obesidade e gdp per capita?